//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPerformanceTests
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class GenericWebTestCode : WebTest
    {

        public GenericWebTestCode()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request1.ExpectedResponseUrl = "https://api.bing.com/qsml.aspx?query=h&maxwidth=32765&rowheight=20&sectionHeight=" +
                "160&FORM=IESS02&market=en-GB";
            request1.QueryStringParameters.Add("query", "h", false, false);
            request1.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request1.QueryStringParameters.Add("rowheight", "20", false, false);
            request1.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request1.QueryStringParameters.Add("FORM", "IESS02", false, false);
            request1.QueryStringParameters.Add("market", "en-GB", false, false);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request2.ExpectedResponseUrl = "https://api.bing.com/qsml.aspx?query=ht&maxwidth=32765&rowheight=20&sectionHeight" +
                "=160&FORM=IESS02&market=en-GB";
            request2.QueryStringParameters.Add("query", "ht", false, false);
            request2.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request2.QueryStringParameters.Add("rowheight", "20", false, false);
            request2.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request2.QueryStringParameters.Add("FORM", "IESS02", false, false);
            request2.QueryStringParameters.Add("market", "en-GB", false, false);
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request3.ExpectedResponseUrl = "https://api.bing.com/qsml.aspx?query=htt&maxwidth=32765&rowheight=20&sectionHeigh" +
                "t=160&FORM=IESS02&market=en-GB";
            request3.QueryStringParameters.Add("query", "htt", false, false);
            request3.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request3.QueryStringParameters.Add("rowheight", "20", false, false);
            request3.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request3.QueryStringParameters.Add("FORM", "IESS02", false, false);
            request3.QueryStringParameters.Add("market", "en-GB", false, false);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request4.ExpectedResponseUrl = "https://api.bing.com/qsml.aspx?query=http&maxwidth=32765&rowheight=20&sectionHeig" +
                "ht=160&FORM=IESS02&market=en-GB";
            request4.QueryStringParameters.Add("query", "http", false, false);
            request4.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request4.QueryStringParameters.Add("rowheight", "20", false, false);
            request4.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request4.QueryStringParameters.Add("FORM", "IESS02", false, false);
            request4.QueryStringParameters.Add("market", "en-GB", false, false);
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request5.ExpectedResponseUrl = "https://api.bing.com/qsml.aspx?query=https&maxwidth=32765&rowheight=20&sectionHei" +
                "ght=160&FORM=IESS02&market=en-GB";
            request5.QueryStringParameters.Add("query", "https", false, false);
            request5.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request5.QueryStringParameters.Add("rowheight", "20", false, false);
            request5.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request5.QueryStringParameters.Add("FORM", "IESS02", false, false);
            request5.QueryStringParameters.Add("market", "en-GB", false, false);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request6.ExpectedResponseUrl = "https://api.bing.com/qsml.aspx?query=https%3A&maxwidth=32765&rowheight=20&section" +
                "Height=160&FORM=IESS02&market=en-GB";
            request6.QueryStringParameters.Add("query", "https%3A", false, false);
            request6.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request6.QueryStringParameters.Add("rowheight", "20", false, false);
            request6.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request6.QueryStringParameters.Add("FORM", "IESS02", false, false);
            request6.QueryStringParameters.Add("market", "en-GB", false, false);
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request7.ThinkTime = 5;
            request7.ExpectedResponseUrl = "https://api.bing.com/qsml.aspx?query=https%3A%2F&maxwidth=524&rowheight=20&sectio" +
                "nHeight=160&FORM=IESS02&market=en-GB";
            request7.QueryStringParameters.Add("query", "https%3A%2F", false, false);
            request7.QueryStringParameters.Add("maxwidth", "524", false, false);
            request7.QueryStringParameters.Add("rowheight", "20", false, false);
            request7.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request7.QueryStringParameters.Add("FORM", "IESS02", false, false);
            request7.QueryStringParameters.Add("market", "en-GB", false, false);
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("https://www.startpage.com/");
            WebTestRequest request8Dependent1 = new WebTestRequest("https://www.startpage.com/font/ProximaNova-Reg-webfont.eot");
            request8Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/"));
            request8Dependent1.QueryStringParameters.Add("", "", false, false);
            request8.DependentRequests.Add(request8Dependent1);
            WebTestRequest request8Dependent2 = new WebTestRequest("https://www.startpage.com/font/ProximaNova-Bold-webfont.eot");
            request8Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/"));
            request8Dependent2.QueryStringParameters.Add("", "", false, false);
            request8.DependentRequests.Add(request8Dependent2);
            WebTestRequest request8Dependent3 = new WebTestRequest("https://www.startpage.com/font/ProximaNovaSoft-Regular-webfont.eot");
            request8Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/"));
            request8Dependent3.QueryStringParameters.Add("", "", false, false);
            request8.DependentRequests.Add(request8Dependent3);
            WebTestRequest request8Dependent4 = new WebTestRequest("https://www.startpage.com/font/Arimo-Regular-webfont.eot");
            request8Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/"));
            request8Dependent4.QueryStringParameters.Add("", "", false, false);
            request8.DependentRequests.Add(request8Dependent4);
            ExtractHiddenFields extractionRule1 = new ExtractHiddenFields();
            extractionRule1.Required = true;
            extractionRule1.HtmlDecode = true;
            extractionRule1.ContextParameterName = "1";
            request8.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule1.Extract);
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("https://www.startpage.com/pelp");
            request9.ThinkTime = 7;
            request9.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/"));
            request9.QueryStringParameters.Add("ct", "1500642519915", false, false);
            request9.QueryStringParameters.Add("tzo", "60", false, false);
            request9.QueryStringParameters.Add("uw", "1920", false, false);
            request9.QueryStringParameters.Add("uh", "1080", false, false);
            request9.QueryStringParameters.Add("bw", "1658", false, false);
            request9.QueryStringParameters.Add("bh", "986", false, false);
            request9.QueryStringParameters.Add("ln", "english_uk", false, false);
            request9.QueryStringParameters.Add("pt", "hp", false, false);
            request9.QueryStringParameters.Add("nc", "1500642519915", false, false);
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("https://www.startpage.com/do/search");
            request10.Method = "POST";
            request10.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/"));
            FormPostHttpBody request10Body = new FormPostHttpBody();
            request10Body.FormPostParameters.Add("hmb", "1");
            request10Body.FormPostParameters.Add("cat", this.Context["$HIDDEN1.cat"].ToString());
            request10Body.FormPostParameters.Add("cmd", this.Context["$HIDDEN1.cmd"].ToString());
            request10Body.FormPostParameters.Add("language", this.Context["$HIDDEN1.language"].ToString());
            request10Body.FormPostParameters.Add("engine0", this.Context["$HIDDEN1.engine0"].ToString());
            request10Body.FormPostParameters.Add("query", "visual studio");
            request10Body.FormPostParameters.Add("abp", this.Context["$HIDDEN1.abp"].ToString());
            request10Body.FormPostParameters.Add("t", this.Context["$HIDDEN1.t"].ToString());
            request10Body.FormPostParameters.Add("nj", "0");
            request10Body.FormPostParameters.Add("pg", "4");
            request10.Body = request10Body;
            WebTestRequest request10Dependent1 = new WebTestRequest("https://www.startpage.com/font/ProximaNova-Reg-webfont.eot");
            request10Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/do/search"));
            request10Dependent1.QueryStringParameters.Add("", "", false, false);
            request10.DependentRequests.Add(request10Dependent1);
            WebTestRequest request10Dependent2 = new WebTestRequest("https://www.ixquick.com/do/instantanswers/iaservice");
            request10Dependent2.Method = "POST";
            request10Dependent2.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request10Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/do/search"));
            StringHttpBody request10Dependent2Body = new StringHttpBody();
            request10Dependent2Body.ContentType = "text/plain; charset=utf-8";
            request10Dependent2Body.InsertByteOrderMark = false;
            request10Dependent2Body.BodyString = "{\"iats\":\"MTUwMDY0MjUyNg==\",\"slang\":\"english_uk\",\"iatoken\":\"bfc441011001ff15b14708" +
                "3c3063ccdb\",\"iasp\":\"fe15cd12102f343cc2b86f9da2d8906d\",\"lang\":\"english_uk\",\"query" +
                "\":\"visual+studio\",\"gl\":\"uk\",\"tz\":-60}";
            request10Dependent2.Body = request10Dependent2Body;
            request10.DependentRequests.Add(request10Dependent2);
            WebTestRequest request10Dependent3 = new WebTestRequest("https://www.startpage.com/font/ProximaNova-Bold-webfont.eot");
            request10Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/do/search"));
            request10Dependent3.QueryStringParameters.Add("", "", false, false);
            request10.DependentRequests.Add(request10Dependent3);
            WebTestRequest request10Dependent4 = new WebTestRequest("https://www.startpage.com/font/Arimo-Regular-webfont.eot");
            request10Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/do/search"));
            request10Dependent4.QueryStringParameters.Add("", "", false, false);
            request10.DependentRequests.Add(request10Dependent4);
            WebTestRequest request10Dependent5 = new WebTestRequest("https://www.startpage.com/gp/wg/afs/ads");
            request10Dependent5.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/do/search"));
            request10Dependent5.QueryStringParameters.Add("q", "visual%20studio", false, false);
            request10Dependent5.QueryStringParameters.Add("lo", "false", false, false);
            request10Dependent5.QueryStringParameters.Add("adpage", "1", false, false);
            request10Dependent5.QueryStringParameters.Add("adrep", "3", false, false);
            request10Dependent5.QueryStringParameters.Add("gl", "uk", false, false);
            request10Dependent5.QueryStringParameters.Add("r", "m", false, false);
            request10Dependent5.QueryStringParameters.Add("fexp", "21404%2C17300002", false, false);
            request10Dependent5.QueryStringParameters.Add("client", "startpage", false, false);
            request10Dependent5.QueryStringParameters.Add("channel", "english_uk%2Bgerman_test%2Benglish_us_test%2Benglish_us_test-ct%2Bgeo_br%2Bct%2Bb" +
                    "rowser_ie%2Ba_low", false, false);
            request10Dependent5.QueryStringParameters.Add("hl", "en", false, false);
            request10Dependent5.QueryStringParameters.Add("adtest", "off", false, false);
            request10Dependent5.QueryStringParameters.Add("adsafe", "medium", false, false);
            request10Dependent5.QueryStringParameters.Add("type", "0", false, false);
            request10Dependent5.QueryStringParameters.Add("oe", "UTF-8", false, false);
            request10Dependent5.QueryStringParameters.Add("ie", "UTF-8", false, false);
            request10Dependent5.QueryStringParameters.Add("jsei", "4", false, false);
            request10Dependent5.QueryStringParameters.Add("format", "p3%7Cn3", false, false);
            request10Dependent5.QueryStringParameters.Add("ad", "n3p3", false, false);
            request10Dependent5.QueryStringParameters.Add("nocache", "7211500642527918", false, false);
            request10Dependent5.QueryStringParameters.Add("num", "0", false, false);
            request10Dependent5.QueryStringParameters.Add("output", "uds_ads_only", false, false);
            request10Dependent5.QueryStringParameters.Add("v", "3", false, false);
            request10Dependent5.QueryStringParameters.Add("adlh", "on", false, false);
            request10Dependent5.QueryStringParameters.Add("adext", "as1%2Csr1", false, false);
            request10Dependent5.QueryStringParameters.Add("bsl", "10", false, false);
            request10Dependent5.QueryStringParameters.Add("u_his", "2", false, false);
            request10Dependent5.QueryStringParameters.Add("u_tz", "60", false, false);
            request10Dependent5.QueryStringParameters.Add("dt", "1500642527920", false, false);
            request10Dependent5.QueryStringParameters.Add("u_w", "1920", false, false);
            request10Dependent5.QueryStringParameters.Add("u_h", "1080", false, false);
            request10Dependent5.QueryStringParameters.Add("biw", "1658", false, false);
            request10Dependent5.QueryStringParameters.Add("bih", "986", false, false);
            request10Dependent5.QueryStringParameters.Add("psw", "1658", false, false);
            request10Dependent5.QueryStringParameters.Add("psh", "986", false, false);
            request10Dependent5.QueryStringParameters.Add("frm", "0", false, false);
            request10Dependent5.QueryStringParameters.Add("uio", "uv3cs1vp1af2da1sr1sl1lHff2st16sd14sv14va1lo0lt22ld19--", false, false);
            request10Dependent5.QueryStringParameters.Add("jsv", "15041", false, false);
            request10Dependent5.QueryStringParameters.Add("rurl", "https%3A%2F%2Fwww.startpage.com%2Fdo%2Fsearch", false, false);
            request10Dependent5.QueryStringParameters.Add("referer", "https%3A%2F%2Fwww.startpage.com%2F", false, false);
            request10.DependentRequests.Add(request10Dependent5);
            WebTestRequest request10Dependent6 = new WebTestRequest("https://www.startpage.com/do/get_zeroclick_info");
            request10Dependent6.Method = "POST";
            request10Dependent6.Headers.Add(new WebTestRequestHeader("Accept", "*/*"));
            request10Dependent6.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request10Dependent6.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/do/search"));
            FormPostHttpBody request10Dependent6Body = new FormPostHttpBody();
            request10Dependent6Body.FormPostParameters.Add("wkt", "54576p6n636q397n62325n3058315n7063335668624639546448566o6157383q");
            request10Dependent6Body.FormPostParameters.Add("ln", "english_uk");
            request10Dependent6Body.FormPostParameters.Add("iasp", "fe15cd12102f343cc2b86f9da2d8906d");
            request10Dependent6Body.FormPostParameters.Add("iats", "MTUwMDY0MjUyNg==");
            request10Dependent6Body.FormPostParameters.Add("iatoken", "773a38b09d80fadbc288bc70da8d5558");
            request10Dependent6.Body = request10Dependent6Body;
            request10.DependentRequests.Add(request10Dependent6);
            WebTestRequest request10Dependent7 = new WebTestRequest("https://www.startpage.com/gp/wg/afs/ads/i/iframe.html");
            request10Dependent7.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/do/search"));
            request10.DependentRequests.Add(request10Dependent7);
            WebTestRequest request10Dependent8 = new WebTestRequest("https://www.startpage.com/font/ProximaNovaSoft-Regular-webfont.eot");
            request10Dependent8.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/do/search"));
            request10Dependent8.QueryStringParameters.Add("", "", false, false);
            request10.DependentRequests.Add(request10Dependent8);
            ExtractHiddenFields extractionRule2 = new ExtractHiddenFields();
            extractionRule2.Required = true;
            extractionRule2.HtmlDecode = true;
            extractionRule2.ContextParameterName = "1";
            request10.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule2.Extract);
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("https://www.startpage.com/elp");
            request11.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/do/search"));
            request11.QueryStringParameters.Add("ct", "1500642528242", false, false);
            request11.QueryStringParameters.Add("tzo", "60", false, false);
            request11.QueryStringParameters.Add("uw", "1920", false, false);
            request11.QueryStringParameters.Add("uh", "1080", false, false);
            request11.QueryStringParameters.Add("bw", "1658", false, false);
            request11.QueryStringParameters.Add("bh", "986", false, false);
            request11.QueryStringParameters.Add("ln", "english_uk", false, false);
            request11.QueryStringParameters.Add("nc", "1500642528242", false, false);
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("https://s7-eu5.startpage.com/pelp");
            request12.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/do/search"));
            request12.QueryStringParameters.Add("ct", "1500642528243", false, false);
            request12.QueryStringParameters.Add("tzo", "60", false, false);
            request12.QueryStringParameters.Add("uw", "1920", false, false);
            request12.QueryStringParameters.Add("uh", "1080", false, false);
            request12.QueryStringParameters.Add("bw", "1658", false, false);
            request12.QueryStringParameters.Add("bh", "986", false, false);
            request12.QueryStringParameters.Add("ln", "english_uk", false, false);
            request12.QueryStringParameters.Add("pt", "rs", false, false);
            request12.QueryStringParameters.Add("nc", "1500642528243", false, false);
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("https://s7-eu5.startpage.com/do//rel_ser");
            request13.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request13.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/do/search"));
            request13.QueryStringParameters.Add("format", "html", false, false);
            request13.QueryStringParameters.Add("qid", this.Context["$HIDDEN1.qid"].ToString(), false, false);
            request13.QueryStringParameters.Add("lui", "english_uk", false, false);
            request13.QueryStringParameters.Add("ssr", "0", false, false);
            request13.QueryStringParameters.Add("with_date", "", false, false);
            request13.QueryStringParameters.Add("src", "", false, false);
            request13.QueryStringParameters.Add("nj", this.Context["$HIDDEN1.nj"].ToString(), false, false);
            request13.QueryStringParameters.Add("hmb", this.Context["$HIDDEN1.hmb"].ToString(), false, false);
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("https://www.startpage.com/font/Arimo-Bold-webfont.eot");
            request14.Headers.Add(new WebTestRequestHeader("Referer", "https://www.startpage.com/do/search"));
            request14.QueryStringParameters.Add("", "", false, false);
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("https://www.visualstudio.com/");
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("https://www.visualstudio.com/");
            WebTestRequest request16Dependent1 = new WebTestRequest("https://logx.optimizely.com/log/event");
            request16Dependent1.Method = "POST";
            request16Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            StringHttpBody request16Dependent1Body = new StringHttpBody();
            request16Dependent1Body.ContentType = "text/plain;charset=UTF-8";
            request16Dependent1Body.InsertByteOrderMark = false;
            request16Dependent1Body.BodyString = @"{""eventId"":""6e94b2e7-8379-4a3d-888c-f4faae3630d8"",""anonymizeIP"":true,""timestamp"":1500642531280,""revision"":""1635"",""clientEngine"":""js"",""clientVersion"":""0.64.0"",""projectId"":""6189442473"",""accountId"":""3698060313"",""activationId"":""63f58b86-af3b-41e4-bb88-bbf1736ad0f6"",""sessionId"":""9c7049d3-939f-41f5-aebe-d5789944435a"",""visitorId"":""oeu1484573729623r0.603002459923891"",""eventFeatures"":[],""eventMetrics"":[],""relatedEvents"":[],""layerStates"":[],""userFeatures"":[{""id"":null,""type"":""first_session"",""name"":"""",""shouldIndex"":true,""value"":true},{""id"":null,""type"":""browserId"",""name"":"""",""shouldIndex"":true,""value"":""ie""},{""id"":null,""type"":""device"",""name"":"""",""shouldIndex"":true,""value"":""desktop""},{""id"":null,""type"":""source_type"",""name"":"""",""shouldIndex"":true,""value"":""direct""},{""id"":null,""type"":""currentTimestamp"",""name"":"""",""shouldIndex"":true,""value"":1500642531279},{""id"":null,""type"":""offset"",""name"":"""",""shouldIndex"":true,""value"":-60}],""activeViews"":[],""isGlobalHoldback"":false,""eventType"":""client_activation"",""eventName"":""client_activation""}";
            request16Dependent1.Body = request16Dependent1Body;
            request16.DependentRequests.Add(request16Dependent1);
            WebTestRequest request16Dependent2 = new WebTestRequest("https://logx.optimizely.com/log/decision");
            request16Dependent2.Method = "POST";
            request16Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            StringHttpBody request16Dependent2Body = new StringHttpBody();
            request16Dependent2Body.ContentType = "text/plain;charset=UTF-8";
            request16Dependent2Body.InsertByteOrderMark = false;
            request16Dependent2Body.BodyString = @"{""decisionId"":""80099425-f8bd-46d7-be75-3df3e8f0b69e"",""anonymizeIP"":true,""timestamp"":1500642531291,""revision"":""1635"",""clientEngine"":""js"",""clientVersion"":""0.64.0"",""projectId"":""6189442473"",""accountId"":""3698060313"",""layerId"":""8462336156"",""activationId"":""63f58b86-af3b-41e4-bb88-bbf1736ad0f6"",""sessionId"":""9c7049d3-939f-41f5-aebe-d5789944435a"",""visitorId"":""oeu1484573729623r0.603002459923891"",""decisionTicket"":{""audiences"":[],""bucketingId"":""oeu1484573729623r0.603002459923891""},""decision"":{""experimentId"":""8458796028"",""variationId"":""8466137646"",""isLayerHoldback"":false},""userFeatures"":[{""id"":null,""type"":""first_session"",""name"":"""",""shouldIndex"":true,""value"":true},{""id"":null,""type"":""browserId"",""name"":"""",""shouldIndex"":true,""value"":""ie""},{""id"":null,""type"":""device"",""name"":"""",""shouldIndex"":true,""value"":""desktop""},{""id"":null,""type"":""source_type"",""name"":"""",""shouldIndex"":true,""value"":""direct""},{""id"":null,""type"":""currentTimestamp"",""name"":"""",""shouldIndex"":true,""value"":1500642531287},{""id"":null,""type"":""offset"",""name"":"""",""shouldIndex"":true,""value"":-60}],""isGlobalHoldback"":false}";
            request16Dependent2.Body = request16Dependent2Body;
            request16.DependentRequests.Add(request16Dependent2);
            WebTestRequest request16Dependent3 = new WebTestRequest("https://www.visualstudio.com/wp-content/uploads/2016/03/segoeui-1.eot");
            request16Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            request16Dependent3.QueryStringParameters.Add("", "", false, false);
            request16.DependentRequests.Add(request16Dependent3);
            WebTestRequest request16Dependent4 = new WebTestRequest("https://www.visualstudio.com/wp-content/uploads/2016/06/latest-1.eot");
            request16Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            request16Dependent4.QueryStringParameters.Add("", "", false, false);
            request16.DependentRequests.Add(request16Dependent4);
            WebTestRequest request16Dependent5 = new WebTestRequest("https://www.visualstudio.com/wp-content/themes/Avada/assets/fonts/fontawesome/fon" +
                    "tawesome-webfont.eot");
            request16Dependent5.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            request16Dependent5.QueryStringParameters.Add("", "", false, false);
            request16.DependentRequests.Add(request16Dependent5);
            WebTestRequest request16Dependent6 = new WebTestRequest("https://assets.onestore.ms/cdnfiles/external/mwf/long/v1/v1.23.2/fonts/MWFMDL2.wo" +
                    "ff");
            request16Dependent6.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            request16.DependentRequests.Add(request16Dependent6);
            WebTestRequest request16Dependent7 = new WebTestRequest("https://fonts.googleapis.com/css");
            request16Dependent7.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            request16Dependent7.QueryStringParameters.Add("family", "Source+Sans+Pro:200%7CMS-Font-Segoe-Regular:400%7CMS-Font-Segoe:400", false, false);
            request16.DependentRequests.Add(request16Dependent7);
            WebTestRequest request16Dependent8 = new WebTestRequest("https://app.vssps.visualstudio.com/_apis/connectionData");
            request16Dependent8.ExpectedResponseUrl = @"https://app.vssps.visualstudio.com/_signin?realm=app.vssps.visualstudio.com&reply_to=https%3A%2F%2Fapp.vssps.visualstudio.com%2F_apis%2FconnectionData%3F_%3D1500642531390&redirect=1&mkt=en-GB&context=eyJodCI6MywiaGlkIjoiYTVjYTM1ZWItMTQ4ZS00Y2NkLWJiYjMtZDMxNTc2ZDc1OTU4IiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSJdfQ2";
            request16Dependent8.Headers.Add(new WebTestRequestHeader("Accept", "*/*"));
            request16Dependent8.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            request16Dependent8.QueryStringParameters.Add("_", "1500642531390", false, false);
            request16.DependentRequests.Add(request16Dependent8);
            WebTestRequest request16Dependent9 = new WebTestRequest("https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGMa9awK0IKUjIWA" +
                    "BZIchFI8.woff");
            request16Dependent9.ThinkTime = 1;
            request16Dependent9.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            request16.DependentRequests.Add(request16Dependent9);
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest("https://a3698060313.cdn.optimizely.com/client_storage/a3698060313.html");
            request17.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest("https://a3698060313.cdn.optimizely.com/client_storage/a3698060313.html");
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest("https://bam.nr-data.net/1/b0106f4dcd");
            request19.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request19.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            request19.QueryStringParameters.Add("a", "17441482", false, false);
            request19.QueryStringParameters.Add("v", "1039.bef6007", false, false);
            request19.QueryStringParameters.Add("to", "YFFQNhYCV0RYVBEKWlkbcwEQClZZFgZVUxhAXVYWDA%3D%3D", false, false);
            request19.QueryStringParameters.Add("rst", "1330", false, false);
            request19.QueryStringParameters.Add("ref", "https://www.visualstudio.com/", false, false);
            request19.QueryStringParameters.Add("ap", "1753", false, false);
            request19.QueryStringParameters.Add("be", "318", false, false);
            request19.QueryStringParameters.Add("fe", "1276", false, false);
            request19.QueryStringParameters.Add("dc", "880", false, false);
            request19.QueryStringParameters.Add("af", "err,xhr,stn,ins,spa", false, false);
            request19.QueryStringParameters.Add("perf", @"%7B%22timing%22:%7B%22of%22:1500642530984,%22n%22:0,%22f%22:0,%22dn%22:0,%22dne%22:0,%22c%22:0,%22ce%22:0,%22rq%22:126,%22rp%22:127,%22rpe%22:142,%22dl%22:127,%22di%22:855,%22ds%22:856,%22de%22:1141,%22dc%22:1274,%22l%22:1276,%22le%22:1324%7D,%22navigation%22:%7B%7D%7D", false, false);
            request19.QueryStringParameters.Add("at", "TBZTQF4YREo%3D", false, false);
            request19.QueryStringParameters.Add("jsonp", "NREUM.setToken", false, false);
            yield return request19;
            request19 = null;

            WebTestRequest request20 = new WebTestRequest("https://app.vssps.visualstudio.com/_apis/profile/profiles/me");
            request20.ExpectedResponseUrl = @"https://app.vssps.visualstudio.com/_signin?realm=app.vssps.visualstudio.com&reply_to=https%3A%2F%2Fapp.vssps.visualstudio.com%2F_apis%2Fprofile%2Fprofiles%2Fme%3F_%3D1500642531391&redirect=1&mkt=en-GB&context=eyJodCI6MywiaGlkIjoiYTVjYTM1ZWItMTQ4ZS00Y2NkLWJiYjMtZDMxNTc2ZDc1OTU4IiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSJdfQ2";
            request20.Headers.Add(new WebTestRequestHeader("Accept", "*/*"));
            request20.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            request20.QueryStringParameters.Add("_", "1500642531391", false, false);
            yield return request20;
            request20 = null;

            WebTestRequest request21 = new WebTestRequest("https://logx.optimizely.com/log/event");
            request21.Method = "POST";
            request21.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            StringHttpBody request21Body = new StringHttpBody();
            request21Body.ContentType = "text/plain;charset=UTF-8";
            request21Body.InsertByteOrderMark = false;
            request21Body.BodyString = "{\"eventId\":\"6f190896-14cc-42e0-a236-2d46232b0661\",\"anonymizeIP\":true,\"timestamp\":" +
                "1500642532388,\"revision\":\"1635\",\"clientEngine\":\"js\",\"clientVersion\":\"0.64.0\",\"pr" +
                "ojectId\":\"6189442473\",\"accountId\":\"3698060313\",\"activationId\":\"63f58b86-af3b-41e" +
                "4-bb88-bbf1736ad0f6\",\"sessionId\":\"9c7049d3-939f-41f5-aebe-d5789944435a\",\"visitor" +
                "Id\":\"oeu1484573729623r0.603002459923891\",\"eventFeatures\":[{\"id\":null,\"shouldInde" +
                "x\":true,\"type\":\"view_category\",\"name\":\"\",\"value\":\"other\"}],\"eventMetrics\":[],\"re" +
                "latedEvents\":[],\"layerStates\":[{\"layerId\":\"8462336156\",\"revision\":\"1635\",\"decisi" +
                "onTicket\":{\"audiences\":[],\"bucketingId\":\"oeu1484573729623r0.603002459923891\"},\"d" +
                "ecision\":{\"experimentId\":\"8458796028\",\"variationId\":\"8466137646\",\"isLayerHoldbac" +
                "k\":false},\"decisionActivationId\":\"63f58b86-af3b-41e4-bb88-bbf1736ad0f6\",\"decisio" +
                "nSessionId\":\"9c7049d3-939f-41f5-aebe-d5789944435a\",\"decisionEventId\":\"80099425-f" +
                "8bd-46d7-be75-3df3e8f0b69e\",\"decisionTimestamp\":1500642531289,\"actionTriggered\":" +
                "true,\"actionSessionId\":\"9c7049d3-939f-41f5-aebe-d5789944435a\",\"actionActivationI" +
                "d\":\"63f58b86-af3b-41e4-bb88-bbf1736ad0f6\",\"actionTimestamp\":1500642531290}],\"use" +
                "rFeatures\":[{\"id\":null,\"type\":\"first_session\",\"name\":\"\",\"shouldIndex\":true,\"valu" +
                "e\":true},{\"id\":null,\"type\":\"browserId\",\"name\":\"\",\"shouldIndex\":true,\"value\":\"ie\"" +
                "},{\"id\":null,\"type\":\"device\",\"name\":\"\",\"shouldIndex\":true,\"value\":\"desktop\"},{\"i" +
                "d\":null,\"type\":\"source_type\",\"name\":\"\",\"shouldIndex\":true,\"value\":\"direct\"},{\"id" +
                "\":null,\"type\":\"currentTimestamp\",\"name\":\"\",\"shouldIndex\":true,\"value\":1500642531" +
                "287},{\"id\":null,\"type\":\"offset\",\"name\":\"\",\"shouldIndex\":true,\"value\":-60}],\"acti" +
                "veViews\":[{\"viewId\":\"8285676958\",\"activatedTimestamp\":1500642531287,\"viewFeature" +
                "s\":[{\"id\":null,\"shouldIndex\":true,\"type\":\"view_category\",\"name\":\"\",\"value\":\"othe" +
                "r\"}]},{\"viewId\":\"8292452861\",\"activatedTimestamp\":1500642531296,\"viewFeatures\":[" +
                "{\"id\":null,\"shouldIndex\":true,\"type\":\"view_category\",\"name\":\"\",\"value\":\"other\"}]" +
                "},{\"viewId\":\"8326220607\",\"activatedTimestamp\":1500642531297,\"viewFeatures\":[{\"id" +
                "\":null,\"shouldIndex\":true,\"type\":\"view_category\",\"name\":\"\",\"value\":\"other\"}]}],\"" +
                "isGlobalHoldback\":false,\"eventEntityId\":\"8285676958\",\"eventType\":\"view_activated" +
                "\",\"eventName\":\"8285676958\"}";
            request21.Body = request21Body;
            yield return request21;
            request21 = null;

            WebTestRequest request22 = new WebTestRequest("https://logx.optimizely.com/log/event");
            request22.Method = "POST";
            request22.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            StringHttpBody request22Body = new StringHttpBody();
            request22Body.ContentType = "text/plain;charset=UTF-8";
            request22Body.InsertByteOrderMark = false;
            request22Body.BodyString = "{\"eventId\":\"08d6d39c-1fde-439e-9707-28d6ddb1fb78\",\"anonymizeIP\":true,\"timestamp\":" +
                "1500642532394,\"revision\":\"1635\",\"clientEngine\":\"js\",\"clientVersion\":\"0.64.0\",\"pr" +
                "ojectId\":\"6189442473\",\"accountId\":\"3698060313\",\"activationId\":\"63f58b86-af3b-41e" +
                "4-bb88-bbf1736ad0f6\",\"sessionId\":\"9c7049d3-939f-41f5-aebe-d5789944435a\",\"visitor" +
                "Id\":\"oeu1484573729623r0.603002459923891\",\"eventFeatures\":[{\"id\":null,\"shouldInde" +
                "x\":true,\"type\":\"view_category\",\"name\":\"\",\"value\":\"other\"}],\"eventMetrics\":[],\"re" +
                "latedEvents\":[],\"layerStates\":[{\"layerId\":\"8462336156\",\"revision\":\"1635\",\"decisi" +
                "onTicket\":{\"audiences\":[],\"bucketingId\":\"oeu1484573729623r0.603002459923891\"},\"d" +
                "ecision\":{\"experimentId\":\"8458796028\",\"variationId\":\"8466137646\",\"isLayerHoldbac" +
                "k\":false},\"decisionActivationId\":\"63f58b86-af3b-41e4-bb88-bbf1736ad0f6\",\"decisio" +
                "nSessionId\":\"9c7049d3-939f-41f5-aebe-d5789944435a\",\"decisionEventId\":\"80099425-f" +
                "8bd-46d7-be75-3df3e8f0b69e\",\"decisionTimestamp\":1500642531289,\"actionTriggered\":" +
                "true,\"actionSessionId\":\"9c7049d3-939f-41f5-aebe-d5789944435a\",\"actionActivationI" +
                "d\":\"63f58b86-af3b-41e4-bb88-bbf1736ad0f6\",\"actionTimestamp\":1500642531290}],\"use" +
                "rFeatures\":[{\"id\":null,\"type\":\"first_session\",\"name\":\"\",\"shouldIndex\":true,\"valu" +
                "e\":true},{\"id\":null,\"type\":\"browserId\",\"name\":\"\",\"shouldIndex\":true,\"value\":\"ie\"" +
                "},{\"id\":null,\"type\":\"device\",\"name\":\"\",\"shouldIndex\":true,\"value\":\"desktop\"},{\"i" +
                "d\":null,\"type\":\"source_type\",\"name\":\"\",\"shouldIndex\":true,\"value\":\"direct\"},{\"id" +
                "\":null,\"type\":\"currentTimestamp\",\"name\":\"\",\"shouldIndex\":true,\"value\":1500642531" +
                "287},{\"id\":null,\"type\":\"offset\",\"name\":\"\",\"shouldIndex\":true,\"value\":-60}],\"acti" +
                "veViews\":[{\"viewId\":\"8285676958\",\"activatedTimestamp\":1500642531287,\"viewFeature" +
                "s\":[{\"id\":null,\"shouldIndex\":true,\"type\":\"view_category\",\"name\":\"\",\"value\":\"othe" +
                "r\"}]},{\"viewId\":\"8292452861\",\"activatedTimestamp\":1500642531296,\"viewFeatures\":[" +
                "{\"id\":null,\"shouldIndex\":true,\"type\":\"view_category\",\"name\":\"\",\"value\":\"other\"}]" +
                "},{\"viewId\":\"8326220607\",\"activatedTimestamp\":1500642531297,\"viewFeatures\":[{\"id" +
                "\":null,\"shouldIndex\":true,\"type\":\"view_category\",\"name\":\"\",\"value\":\"other\"}]}],\"" +
                "isGlobalHoldback\":false,\"eventEntityId\":\"8292452861\",\"eventType\":\"view_activated" +
                "\",\"eventName\":\"8292452861\"}";
            request22.Body = request22Body;
            yield return request22;
            request22 = null;

            WebTestRequest request23 = new WebTestRequest("https://logx.optimizely.com/log/event");
            request23.Method = "POST";
            request23.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            StringHttpBody request23Body = new StringHttpBody();
            request23Body.ContentType = "text/plain;charset=UTF-8";
            request23Body.InsertByteOrderMark = false;
            request23Body.BodyString = "{\"eventId\":\"9ee484c2-e829-40df-be02-b4d1bd7ac93b\",\"anonymizeIP\":true,\"timestamp\":" +
                "1500642532399,\"revision\":\"1635\",\"clientEngine\":\"js\",\"clientVersion\":\"0.64.0\",\"pr" +
                "ojectId\":\"6189442473\",\"accountId\":\"3698060313\",\"activationId\":\"63f58b86-af3b-41e" +
                "4-bb88-bbf1736ad0f6\",\"sessionId\":\"9c7049d3-939f-41f5-aebe-d5789944435a\",\"visitor" +
                "Id\":\"oeu1484573729623r0.603002459923891\",\"eventFeatures\":[{\"id\":null,\"shouldInde" +
                "x\":true,\"type\":\"view_category\",\"name\":\"\",\"value\":\"other\"}],\"eventMetrics\":[],\"re" +
                "latedEvents\":[],\"layerStates\":[{\"layerId\":\"8462336156\",\"revision\":\"1635\",\"decisi" +
                "onTicket\":{\"audiences\":[],\"bucketingId\":\"oeu1484573729623r0.603002459923891\"},\"d" +
                "ecision\":{\"experimentId\":\"8458796028\",\"variationId\":\"8466137646\",\"isLayerHoldbac" +
                "k\":false},\"decisionActivationId\":\"63f58b86-af3b-41e4-bb88-bbf1736ad0f6\",\"decisio" +
                "nSessionId\":\"9c7049d3-939f-41f5-aebe-d5789944435a\",\"decisionEventId\":\"80099425-f" +
                "8bd-46d7-be75-3df3e8f0b69e\",\"decisionTimestamp\":1500642531289,\"actionTriggered\":" +
                "true,\"actionSessionId\":\"9c7049d3-939f-41f5-aebe-d5789944435a\",\"actionActivationI" +
                "d\":\"63f58b86-af3b-41e4-bb88-bbf1736ad0f6\",\"actionTimestamp\":1500642531290}],\"use" +
                "rFeatures\":[{\"id\":null,\"type\":\"first_session\",\"name\":\"\",\"shouldIndex\":true,\"valu" +
                "e\":true},{\"id\":null,\"type\":\"browserId\",\"name\":\"\",\"shouldIndex\":true,\"value\":\"ie\"" +
                "},{\"id\":null,\"type\":\"device\",\"name\":\"\",\"shouldIndex\":true,\"value\":\"desktop\"},{\"i" +
                "d\":null,\"type\":\"source_type\",\"name\":\"\",\"shouldIndex\":true,\"value\":\"direct\"},{\"id" +
                "\":null,\"type\":\"currentTimestamp\",\"name\":\"\",\"shouldIndex\":true,\"value\":1500642531" +
                "287},{\"id\":null,\"type\":\"offset\",\"name\":\"\",\"shouldIndex\":true,\"value\":-60}],\"acti" +
                "veViews\":[{\"viewId\":\"8285676958\",\"activatedTimestamp\":1500642531287,\"viewFeature" +
                "s\":[{\"id\":null,\"shouldIndex\":true,\"type\":\"view_category\",\"name\":\"\",\"value\":\"othe" +
                "r\"}]},{\"viewId\":\"8292452861\",\"activatedTimestamp\":1500642531296,\"viewFeatures\":[" +
                "{\"id\":null,\"shouldIndex\":true,\"type\":\"view_category\",\"name\":\"\",\"value\":\"other\"}]" +
                "},{\"viewId\":\"8326220607\",\"activatedTimestamp\":1500642531297,\"viewFeatures\":[{\"id" +
                "\":null,\"shouldIndex\":true,\"type\":\"view_category\",\"name\":\"\",\"value\":\"other\"}]}],\"" +
                "isGlobalHoldback\":false,\"eventEntityId\":\"8326220607\",\"eventType\":\"view_activated" +
                "\",\"eventName\":\"8326220607\"}";
            request23.Body = request23Body;
            yield return request23;
            request23 = null;

            WebTestRequest request24 = new WebTestRequest("https://bam.nr-data.net/events/1/b0106f4dcd");
            request24.Method = "POST";
            request24.Headers.Add(new WebTestRequestHeader("Referer", "https://www.visualstudio.com/"));
            request24.QueryStringParameters.Add("a", "17441482", false, false);
            request24.QueryStringParameters.Add("v", "1039.bef6007", false, false);
            request24.QueryStringParameters.Add("to", "YFFQNhYCV0RYVBEKWlkbcwEQClZZFgZVUxhAXVYWDA%3D%3D", false, false);
            request24.QueryStringParameters.Add("rst", "1604", false, false);
            request24.QueryStringParameters.Add("ref", "https://www.visualstudio.com/", false, false);
            StringHttpBody request24Body = new StringHttpBody();
            request24Body.ContentType = "text/plain";
            request24Body.InsertByteOrderMark = false;
            request24Body.BodyString = "bel.3;1,2,,18e,18e,ai,\'initialPageLoad,\'https://www.visualstudio.com/,1,1,,,,1cp," +
                "!!;a,\'TBZTQF4YREo=;2,,kb,gx,6,2,\'GET,5n,\'app.vssps.visualstudio.com:443,\'/_apis/" +
                "connectionData,,aeo,;b,!!!!,,,,!,3i,1,f,-f,k8,1,7x,3p,2,1c";
            request24.Body = request24Body;
            yield return request24;
            request24 = null;
        }
    }
}
