//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metrics_Dashboard.Models
{
    using System;
    
    public partial class prMessagesProcessedByDay_Result
    {
        public Nullable<System.Guid> Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> MessagesProcessed { get; set; }
    }
}
